
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ashbo
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setSize(466,588);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        first = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        last = new javax.swing.JTextField();
        pass2 = new javax.swing.JPasswordField();
        pass1 = new javax.swing.JPasswordField();
        cancel = new javax.swing.JButton();
        register1 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        address = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("REGISTER");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 153), new java.awt.Color(102, 255, 204), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 204, 153)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 30, 250, 60);

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 350, 100, 30);

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 210, 130, 30);

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Last Name:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 160, 130, 30);

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Name:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 110, 140, 30);

        first.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });
        getContentPane().add(first);
        first.setBounds(180, 110, 210, 30);

        username.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(180, 210, 210, 30);

        last.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastActionPerformed(evt);
            }
        });
        getContentPane().add(last);
        last.setBounds(180, 160, 210, 30);

        pass2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass2ActionPerformed(evt);
            }
        });
        getContentPane().add(pass2);
        pass2.setBounds(180, 300, 210, 30);

        pass1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass1ActionPerformed(evt);
            }
        });
        getContentPane().add(pass1);
        pass1.setBounds(180, 260, 210, 30);

        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setFont(new java.awt.Font("Dubai", 1, 20)); // NOI18N
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelMousePressed(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(110, 450, 100, 35);

        register1.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        register1.setForeground(new java.awt.Color(153, 255, 255));
        register1.setText("Log in to an existing account");
        register1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                register1MousePressed(evt);
            }
        });
        getContentPane().add(register1);
        register1.setBounds(130, 500, 200, 21);

        register.setBackground(new java.awt.Color(255, 255, 255));
        register.setFont(new java.awt.Font("Dubai", 1, 20)); // NOI18N
        register.setText("Register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register);
        register.setBounds(250, 450, 120, 35);

        address.setColumns(20);
        address.setRows(5);
        getContentPane().add(address);
        address.setBounds(180, 350, 210, 80);

        jLabel11.setFont(new java.awt.Font("Dubai", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 260, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\college\\sy com sci\\oop\\background.PNG")); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastActionPerformed

    private void pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass1ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    private void pass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass2ActionPerformed

    private void register1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register1MouseClicked
        Login login = new Login();
        login.setVisible(true);
        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_register1MouseClicked

    private void register1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register1MousePressed

    }//GEN-LAST:event_register1MousePressed

    private void cancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMousePressed

    }//GEN-LAST:event_cancelMousePressed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        String fir=first.getText(); 
        String las=last.getText(); 
        String user=username.getText();
        String pas1=pass1.getText();
        String pas2=pass2.getText();
        boolean retval1=pas2.equals(pas1);
        if((fir.length()>1)&&(las.length()>1)&&(user.length()>1)&&(pas1.length()>1)&&(retval1))
        {
            JOptionPane.showMessageDialog(this,"Registered successfully","Register",JOptionPane.PLAIN_MESSAGE);
            first.setText("");
            last.setText("");
            username.setText("");
            pass1.setText("");
            pass2.setText("");
            address.setText("");
        }
        else if(fir.length()<1)
        {
            JOptionPane.showMessageDialog(this,"Invalid First name","Register",JOptionPane.PLAIN_MESSAGE);
        }
        else if(las.length()<1)
        {
            JOptionPane.showMessageDialog(this,"Invalid Last name","Register",JOptionPane.PLAIN_MESSAGE);
        }
        else if(user.length()<1)
        {
            JOptionPane.showMessageDialog(this,"Invalid Username","Register",JOptionPane.PLAIN_MESSAGE);
        }
        else if(pas1.length()<1)
        {
            JOptionPane.showMessageDialog(this,"Enter Password","Register",JOptionPane.PLAIN_MESSAGE);
        }
        else if(pas2.length()<1)
        {
            JOptionPane.showMessageDialog(this,"Enter confirmation password","Register",JOptionPane.PLAIN_MESSAGE);
        }
        else if(!retval1)
        {
            JOptionPane.showMessageDialog(this,"Password doesnt match","Register",JOptionPane.PLAIN_MESSAGE);
            pass1.setText("");
            pass2.setText("");
        }
    }//GEN-LAST:event_registerMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        first.setText("");
        last.setText("");
        username.setText("");
        pass1.setText("");
        pass2.setText("");
        last.setText("");
        address.setText("");
    }//GEN-LAST:event_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField first;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField last;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JButton register;
    private javax.swing.JLabel register1;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
